### ISSUE TITLE
BioGRID adapter not working

### ISSUE THREAD

**Issue by alexandre239** [HUBioDataLab/CROssBAR-BioCypher-Migration#10]
Hi,

I have just attempted to use the BioGRID adapter to download data from BioGRID and have come to the following error (see below). I checked with one of the biocypher's developers (@slobentanzer) and this problem seems to be on the adapter's side. Please let me know when can this be fixed, thanks.

from biogrid_adapter import BioGRID
yeast_biogrid = BioGRID(organism=9606, export_csvs=True, output_dir='./', test_mode=True)
yeast_biogrid.download_biogrid_data()

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[3], line 1
----> 1 yeast_biogrid.download_biogrid_data()

File /biocypher/biogrid_adapter.py:119, in BioGRID.download_biogrid_data(self)
    116     self.biogrid_ints = biogrid.biogrid_all_interactions(self.organism, 9999999999, False)
    118     # download these fields for mapping from gene symbol to uniprot id          
--> 119     self.uniprot_to_gene = uniprot.uniprot_data("genes", "*", True)
    120     self.uniprot_to_tax = uniprot.uniprot_data("organism-id", "*", True)
    123 if self.test_mode:

File /biocypher/.venv/lib/python3.10/site-packages/pypath/inputs/uniprot.py:566, in uniprot_data(field, organism, reviewed)
    563     get['query'] = rev.strip(' AND ')
    565 c = curl.Curl(url, get = get, silent = False, large = True, compr = 'gz')
--> 566 _ = next(c.result)
    569 _id, *variables = zip(*(
    570     line.strip('\n\r').split('\t')
    571     for line in c.result if line.strip('\n\r')
    572 ))
    574 result = dict(
    575     (
    576         f,
   (...)
    579     for f, v in zip(field, variables)
    580 )

TypeError: 'NoneType' object is not an iterator

**Comment by bnymnsen** [comment]
Hi, sorry for answering a bit late. This is due to latest migration of pypath to uniprot rest api. I changed the field names for that api (a275ef1d6f035f63dcc5e9de78b19a299b01c8af), I think it should work fine now.

**Comment by alexandre239** [comment]
Hi! Thanks for fixing, is it possible to download these changes without having to do it manually? Thanks again

**Comment by alexandre239** [comment]
Hi! I have downloaded the updated file and re-run the same code as shown above, and getting the same error:

```
INFO -- This is the link of BioGRID data we downloaded:http://thebiogrid.org/downloads/archives/Latest%20Release/BIOGRID-ALL-LATEST.tab2.zip. Please check if it is up to date
<class 'TypeError'>, 'NoneType' object is not an iterator, <traceback object at 0x7f446d76e4c0>
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[6], line 1
----> 1 yeast_biogrid.download_biogrid_data()

File [/aloy/home/acasadesus/AC_yeast_project/biocypher/biogrid_adapter.py:119](https://file+.vscode-resource.vscode-cdn.net/aloy/home/acasadesus/AC_yeast_project/biocypher/biogrid_adapter.py:119), in BioGRID.download_biogrid_data(self)
    116     self.biogrid_ints = biogrid.biogrid_all_interactions(self.organism, 9999999999, False)
    118     # download these fields for mapping from gene symbol to uniprot id          
--> 119     self.uniprot_to_gene = uniprot.uniprot_data("gene_names", "*", True)
    120     self.uniprot_to_tax = uniprot.uniprot_data("organism_id", "*", True)
    123 if self.test_mode:

File [/aloy/home/acasadesus/AC_yeast_project/biocypher/.venv/lib/python3.10/site-packages/pypath/inputs/uniprot.py:566](https://file+.vscode-resource.vscode-cdn.net/aloy/home/acasadesus/AC_yeast_project/biocypher/.venv/lib/python3.10/site-packages/pypath/inputs/uniprot.py:566), in uniprot_data(field, organism, reviewed)
    563     get['query'] = rev.strip(' AND ')
    565 c = curl.Curl(url, get = get, silent = False, large = True, compr = 'gz')
--> 566 _ = next(c.result)
    569 _id, *variables = zip(*(
    570     line.strip('\n\r').split('\t')
    571     for line in c.result if line.strip('\n\r')
    572 ))
    574 result = dict(
    575     (
    576         f,
   (...)
    579     for f, v in zip(field, variables)
    580 )

TypeError: 'NoneType' object is not an iterator
```
Is there something I am missing? Thank you!

**Comment by slobentanzer** [comment]
I get the same (stacktrace below). Unfortunately need to travel and other things, so cannot look into it right now; @bnymnsen could you help?

FWIW, this seems to be a secondary issue (of the BioGRID adapter calling the uniprot adapter); the error originates in the uniprot adapter. Maybe the API call to the uniprot adapter in the BioGRID adapter needs to be updated?

```
INFO -- This is BioCypher v0.5.17.
INFO -- Logging into `biocypher-log/biocypher-20230904-183114.log`.
INFO -- This is the link of BioGRID data we downloaded:http://thebiogrid.org/downloads/archives/Latest%20Release/BIOGRID-ALL-LATEST.tab2.zip. Please check if it is up to date
<class 'TypeError'>, 'NoneType' object is not an iterator, <traceback object at 0x11d7ef300>
Traceback (most recent call last):
  File "/Users/slobentanzer/GitHub/CROssBAR-BioCypher-Migration/scripts/create_crossbar.py", line 221, in <module>
    main()
  File "/Users/slobentanzer/GitHub/CROssBAR-BioCypher-Migration/scripts/create_crossbar.py", line 115, in main
    yeast_biogrid.download_biogrid_data()
  File "/Users/slobentanzer/GitHub/CROssBAR-BioCypher-Migration/bccb/biogrid_adapter.py", line 119, in download_biogrid_data
    self.uniprot_to_gene = uniprot.uniprot_data("gene_names", "*", True)
  File "/Users/slobentanzer/GitHub/CROssBAR-BioCypher-Migration/.venv/lib/python3.10/site-packages/pypath/inputs/uniprot.py", line 566, in uniprot_data
    _ = next(c.result)
TypeError: 'NoneType' object is not an iterator
```

**Comment by bnymnsen** [comment]
I think, this error is most likely related pypath's uniprot script. Both errors occur when the following function is called in that script: https://github.com/saezlab/pypath/blob/137f24a335abb94aa78610e278e2e07097420466/pypath/inputs/uniprot.py#L505.

Can you guys try following code snippet to see whether or not it is working? If it works, then the error is probably related to timeout settings in pypath. It is in this https://github.com/saezlab/pypath/blob/137f24a335abb94aa78610e278e2e07097420466/pypath/data/settings.yaml#L113 file, you can increase it from there.

```
from pypath.inputs import uniprot

uniprot_to_gene = uniprot.uniprot_data("gene_names", "9606", True)
```

**Comment by deeenes** [comment]
The reason should be clear from the pypath log
