### ISSUE TITLE
Unable to download edge data InterPro adapter

### ISSUE THREAD

**Issue by alexandre239** [HUBioDataLab/CROssBAR-BioCypher-Migration#11]
Hi,

I recently started to use the InterPro adapter and turns out I am unable to download edge data as there seems to be an error coming from pypath in retrieving the input data, please see the code and error below (note that node data was downloaded without any issues, though):

**Code**
```
from interpro_adapter import InterPro
yeast_interpro_1 = InterPro(organism=559292) # S. cerevisiae S-559292
yeast_interpro_1.download_domain_node_data()
yeast_interpro_1.download_domain_edge_data()
```

**Error**
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[6], line 2
      1 # Downloading all edges from interpro
----> 2 yeast_interpro_1.download_domain_edge_data()

File [/acasadesus/AC_yeast_project/biocypher/interpro_adapter.py:163](https://file+.vscode-resource.vscode-cdn.net/acasadesus/AC_yeast_project/biocypher/interpro_adapter.py:163), in InterPro.download_domain_edge_data(self)
    159 t0 = time()
    161 if self.organism:                
    162     # WARNING: decrease page_size parameter if there is a curl error about timeout in the pypath_log
--> 163     self.interpro_annotations = interpro.interpro_annotations(page_size = self.page_size, reviewed = True, tax_id = self.organism)
    164 else:
    165     self.interpro_annotations = interpro.interpro_annotations(page_size = self.page_size, reviewed = True, tax_id = '')

File [/acasadesus/AC_yeast_project/biocypher/.venv/lib/python3.10/site-packages/pypath/inputs/interpro.py:274](https://file+.vscode-resource.vscode-cdn.net/acasadesus/AC_yeast_project/biocypher/.venv/lib/python3.10/site-packages/pypath/inputs/interpro.py:274), in interpro_annotations(page_size, reviewed, tax_id)
    267 c = curl.Curl(
    268     next_page_url,
    269     silent = False,
    270     large = False
    271 )
    273 res = inputs_common.json_read(c.result)
--> 274 totalrec = int(res['count'])
    276 _log(
    277     'Downloading page %u (total: %s).' % (
    278         page + 1,
   (...)
    282     )
    283 )
    285 for entry in res['results']:

TypeError: 'NoneType' object is not subscriptable
```

Be aware that I attempted to change the _page_size_ parameter to 100, 50, 20, 10 as it is advised to be reduced if encountering any curl errors as in my case, but the error persisted anyway (and then even tried to increase it to 200 and 500, just in case).

Would anybody be so kind to look into this and let me know if I am missing something or if indeed there is any problem to be fixed? I presume it is only pypath related.

Thanks!

**Comment by bnymnsen** [comment]
Hi,

As you correctly assume this is a pypath related issue. Can you check given link in pypath_log for retrieving data? I recommend you to open an issue with your pypath log in pypath's github repo.

I also tried to retrieve data for Mus musculus and  S. cerevisiae and encountered same error. I guess the problem is related to interpro api call for annotations.

P.S. The tax id given for Saccharomyces cerevisiae on the interpro website is 4932.

**Comment by alexandre239** [comment]
Hi,

I will inform the pypath team about this. The thing is that pypath has been giving many curl errors with different adapters, so I might as well change the way I retrieve input data myself from now on. 

Yes, you are right about the tax id! However, mostly annotations are rather linked to S. cerevisiae reference strain S288C with tax id 559292, as it is the reference strained most widely used in research.

Thanks!
