### ISSUE TITLE
Break up PPI adapter into individual resources

### ISSUE THREAD

**Issue by slobentanzer** [HUBioDataLab/CROssBAR-BioCypher-Migration#6]
It should be relatively easy to modularise the existing PPI adapter into the three input resources, which is more aligned with the BioCypher design philosophy.

**Comment by bnymnsen** [comment]
Yeah, I can do that. What do you think about merging operation then? Should it be in another script?

**Comment by slobentanzer** [comment]
Merging IMO should be an integral part of BioCypher (such that you can add other resources later and don't need to integrate them manually). We can implement functionality to take care of the merging of properties, for instance.

For instance, we could extend the property configuration like so:
```
protein:
   ...
   properties:
      pubmed:
         - pmid
         - pubmedid
         - ...
```

You can do it in a script at first, if you don't want to immediately go all the way to BioCypher. We can introduce one layer of abstraction at a time. Monolithic manual script -> modular manual script -> upstream in BioCypher.
