### ISSUE TITLE
cannot import name 'IntactEdgeField' from 'bccb.ppi_adapter'

### ISSUE THREAD

**Issue by WagnerJon** [HUBioDataLab/CROssBAR-BioCypher-Migration#8]
Hi, I just cloned the repository, ran "create_crossbar.py" and ran into the following error:

cannot import name 'IntactEdgeField' from 'bccb.ppi_adapter' (C:\Users\Name\Crossbar_to_biocypher\CROssBAR-BioCypher-Migration\bccb\ppi_adapter.py)

However when removing the "s" from the "IntactEdgeFields"/"BiogridEdgeFields"/"StringEdgeFields" classes in the ppi_adapter, it seems to work/download the uniprot data.

I´m still running into another issue further in the execution that I´m not sure about if it is related to this. This is the 2nd error I get:
INFO -- Downloading uniprot data...
100%|██████████| 14/14 [00:00<00:00, 21.93it/s]
INFO -- Acquired UniProt data in 0.07 mins.
INFO -- Preprocessing UniProt data.
100%|██████████| 14/14 [00:03<00:00,  3.53it/s]
Traceback (most recent call last):

  File ~\.conda\envs\biocypher\lib\site-packages\spyder_kernels\py3compat.py:356 in compat_exec
    exec(code, globals, locals)

  File c:\users\name\crossbar_to_biocypher\crossbar-biocypher-migration\create_crossbar.py:133
    main()

  File c:\users\name\crossbar_to_biocypher\crossbar-biocypher-migration\create_crossbar.py:101 in main
    driver.write_nodes(uniprot_adapter.get_nodes())

  File ~\biocypher\biocypher\_core.py:239 in write_nodes
    self._get_writer()

  File ~\biocypher\biocypher\_core.py:203 in _get_writer
    translator=self._get_translator(),

  File ~\biocypher\biocypher\_core.py:173 in _get_translator
    self._translator = Translator(

  File ~\biocypher\biocypher\_translate.py:69 in __init__
    self._update_ontology_types()

  File ~\biocypher\biocypher\_translate.py:396 in _update_ontology_types
    self._add_translation_mappings(labels, value['label_as_edge'])

  File ~\biocypher\biocypher\_translate.py:472 in _add_translation_mappings
    self.mappings[on] = self.name_sentence_to_pascal(

  File ~\biocypher\biocypher\_translate.py:500 in name_sentence_to_pascal
    return _misc.sentencecase_to_pascalcase(name)

  File ~\biocypher\biocypher\_misc.py:205 in sentencecase_to_pascalcase
    return re.sub(r'(?:^| )([a-zA-Z])', lambda match: match.group(1).upper(), s)

  File ~\.conda\envs\biocypher\lib\re.py:209 in sub
    return _compile(pattern, flags).sub(repl, string, count)

TypeError: expected string or bytes-like object

Let me know if I should open a seperate issue for the 2nd error. Thanks in advance!

**Comment by slobentanzer** [comment]
Hi @WagnerJon, thanks for the report. I think the edges creation in that script is still work in progress, I am not sure the `ppi_adapter` is even in use any more, since we wanted to switch to individual adapters for each resource (and PPI is three protein-protein interaction resources in one). I think @bnymnsen knows more about that. Sorry for the confusion, we need to update the script on main.

For now, I have removed references to PPI in the main script, we can add them back when we have decided how to implement it.

The second error seems unrelated though, I will check into it. No need to open a separate issue.

**Comment by slobentanzer** [comment]
OK, the second error is related to the schema definition. We had an experiment with multiple edge labels, that functionality is not yet in the main BioCypher version (there is a PR on BioCypher that I haven't been able to merge yet). It is currently not used in the script, so as a short term solution I commented out these entries in the schema definition. The `create_crossbar.py` script should work now, but please note that this is probably not the current version of the CROssBAR build script, which @bnymnsen works on. Maybe he can shed light on where a more current version lives. :)

**Comment by slobentanzer** [comment]
Closing this now, feel free to reopen or create a new one if something comes up.
